'use client'

import { useCallback } from 'react'
import { useLocale, useMessages } from 'next-intl'
import {
    getPeriodCategoryLabel,
    getPeriodLabel,
    getPeriodTypeLabel,
    localizeFixedPeriodName,
} from '@/utils/i18n/periods'

/*
 * Period, period type and period category display names in the language of the portal.
 * */
export function usePeriodLabels() {
    const locale = useLocale()
    const messages = useMessages()

    const periodLabel = useCallback(
        (periodId: string, fallback?: string) =>
            getPeriodLabel(periodId, { locale, messages, fallback }),
        [locale, messages]
    )

    const periodTypeLabel = useCallback(
        (
            periodTypeId: string,
            category: 'RELATIVE' | 'FIXED',
            fallback?: string
        ) => getPeriodTypeLabel(periodTypeId, category, { messages, fallback }),
        [messages]
    )

    const periodCategoryLabel = useCallback(
        (category: string) => getPeriodCategoryLabel(category, { messages }),
        [messages]
    )

    /*
     * Localizes the name of a fixed period generated by @dhis2/multi-calendar-dates with the current locale
     * */
    const fixedPeriodName = useCallback(
        (name: string) => localizeFixedPeriodName(name, locale, messages),
        [locale, messages]
    )

    return {
        locale,
        periodLabel,
        periodTypeLabel,
        periodCategoryLabel,
        fixedPeriodName,
    }
}
